Exo1-Route/Models/ErrorViewModel.cs
using System;

namespace Exo1_Route.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Exo1-Route/Models/Film.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Models
{
    public class Film
    {
        public string Titre { get; set; }
        public string Poster { get; set; }

        public Film(string titre, string poster)
        {
            Titre = titre;
            Poster = poster;
        }
    }
}

Exo1-Route/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Models
{
    public class Product
    {
        public string Nom { get; set; }
        public double Prix { get; set; }
        public int Stock { get; set; }

        public Product(string nom, double prix, int stock)
        {
            Nom = nom;
            Prix = prix;
            Stock = stock;
        }
    }
}

Exo1-Route/Models/ViewModel/FilmIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Models.ViewModel
{
    public class FilmIndexViewModel
    {
        public List<Film> Films { get; set; }
    }
}

Exo1-Route/Models/ViewModel/ProductIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Models.ViewModel
{
    public class ProductIndexViewModel
    {
        public List<Product> Products { get; set; }

        public ProductIndexViewModel(IEnumerable<Product> products)
        {
            Products = new List<Product>();
            foreach (Product product in products)
            {
                Products.Add(product);
            }
        }
    }
}

Exo1-Route/Controllers/FilmController.cs
using Exo1_Route.Models;
using Exo1_Route.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Controllers
{
    public class FilmController : Controller
    {
        public IActionResult Index()
        {
            FilmIndexViewModel modelfilm = new FilmIndexViewModel();
            modelfilm.Films = new List<Film>()
            {
                new Film("Drop", "/img/drop.jpg"),
                new Film("Dungeons and Dragons: Honor Among Thieves", "/img/dungeons_and_dragons_honor_among_thieves_ver3.jpg"),
                new Film("80", "/img/eighty_for_brady.jpg"),
                new Film("Infinity Pool", "/img/infinity_pool.jpg"),
                new Film("La Brigade", "/img/la_brigade_ver2.jpg"),
                new Film("Night At The Museum: Kahmunrah Rises Again", "/img/night_at_the_museum_kahmunrah_rises_again_ver2.jpg"),
                new Film("Snow Day", "/img/snow_day.jpg"),
                new Film("This Place Rules", "/img/this_place_rules.jpg")
            };
            return View(modelfilm);
        }
    }
}

Exo1-Route/Controllers/HomeController.cs
using Exo1_Route.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Exo1-Route/Controllers/MathController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Controllers
{
    public class MathController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("Math/Carre/{id}")]
        [Route("Math/{id}/auCarre")]
        public int Carre(int id)
        {
            return id * id;
        }

        [Route("Math/Table/{id}")]
        [Route("Math/Multiple/{id}")]
        public string Multiple(int id)
        {
            string result = $"Table de multiplication de {id}\n";
            for (int i = 1; i <= 10 ; i++)
            {
                result += $"{i} x {id} = {i * id}\n";
            }
            return result; 
        }

        [Route("Math/{nb1}/divisePar/{nb2}")]
        [Route("Math/Division/{nb1?}/{nb2?}")]
        public string Division(int nb1, int nb2)
        {
            if (nb2 == 0)
            {
                return "Attention, la division par 0 est impossible !";
            }
            return (nb1 / (double)nb2).ToString();
            //return $"{nb1} / {nb2} = {nb1 / (double)nb2}";
        }

        public IActionResult TableauCroise()
        {
            return View();
        }

    }
}

Exo1-Route/Controllers/ProductController.cs
using Exo1_Route.Models;
using Exo1_Route.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Exo1_Route.Controllers
{
    public class ProductController : Controller
    {
        //public string Title = "Shopping"; 
        //ViewData["title"] = "Shooping";
        public IActionResult Index()
        {
            ViewData["Title"] = "Shopping";
            //ViewData["title"] = Title + ", faîtes votre choix!ss";
            ProductIndexViewModel model = new ProductIndexViewModel(
                new List<Product>
                {
                    new Product("carnet", 4.5, 256),
                    new Product("stylo plume", 9.9, 150),
                    new Product("effaceur", 1.8, 85),
                    new Product("plumier", 12.5, 652),
                    new Product("boîte à tartines", 6.3, 54),
                    new Product("agenda", 6.5, 23)

                }
            );

            return View(model);
        }
    }
}

Exo1-Route/Views/Film/Index.cshtml
@using Exo1_Route.Models.ViewModel;
@model FilmIndexViewModel
@*<h1>@Model.Films[0].Titre</h1>*@
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">

        @if (Model.Films.Count > 0)
        {
            @* @for (int i = 0; i < Model.Films.Count; i++)*@
            foreach (Film film in Model.Films)
            {
                if (film == Model.Films[0])
                {
                    <div class="carousel-item active">
                        <img src="@film.Poster" class="d-block w-100">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>@film.Titre</h5>

                        </div>
                    </div>
                }
                else
                {
                    <div class="carousel-item">
                        <img src="@film.Poster" class="d-block w-100">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>@film.Titre</h5>
                        </div>
                    </div>

                }
            }
        }
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

Exo1-Route/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Exo1-Route/Views/Math/TableauCroise.cshtml
<body>

    @{
        void createTable(int size)
        {
            <table>
                <tbody>
                    @for (int i = 1; i < size; i++)
                    {
                        <tr>
                            @for (int j = 1; j < size; j++)
                            {
                                <td width="50" height="50" style="border: 1px solid black;" align="center">@(i*j)</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
    }

    <h1>Table de multiplication</h1>

    @{createTable(25);}

</body>

Exo1-Route/Views/Product/Index.cshtml
@using Exo1_Route.Models.ViewModel;
@model ProductIndexViewModel

@{
    ViewData["Title"] = "Shopping";
}

<h1>@ViewData["Title"], faîtes votre choix!</h1>

@{
    int count = Model.Products.Count;
}

@if (count > 0)
{
    <ul>
        @foreach (Product product in Model.Products)
        {
            <li>@product.Nom coute @product.Prix (stock disponible = @product.Stock)</li>
        }
        <li>Nombre de produit affiche = @count</li>
    </ul>
}

Exo1-Route/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exo1_Route</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Exo1_Route</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Math" asp-action="TableauCroise">Multiplication</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Exo1_Route - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>